services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    environment:
      VAULT_ADDR: https://localhost:8200
      VAULT_API_ADDR: https://0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
    cap_add:
      - IPC_LOCK
    expose:
      - 8200
    ports:
      - "8200:8200"
    command: vault server -dev-tls -dev-listen-address=0.0.0.0:8200

  one-time-secret:
    build: ./
    # image: ghcr.io/swissbuechi/one-time-secret:latest
    container_name: one-time-secret
    environment:
      VAULT_SKIP_VERIFY: true
      VAULT_ADDR: https://vault:8200
      VAULT_TOKEN: root
      OTS_HTTP_BINDING_ADDRESS: ":80"
      OTS_HTTP_REQUEST_LOG: true
    ports:
      - "8080:80"
    depends_on:
      - vault
