version: '3.8'

services:
  vault:
    image: vault:1.13.1
    container_name: vault
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
    cap_add:
      - IPC_LOCK
    expose:
      - 8200
    ports:
      - "8200:8200"

  one-time-secret:
    build: ./
    # image: ghcr.io/swissbuechi/one-time-secret:1.0.0
    container_name: one-time-secret
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
      OTS_HTTP_BINDING_ADDRESS: ":80"
    ports:
      - "8080:80"
    depends_on:
      - vault
