version: '3.8'

services:
  vault:
    image: vault:1.13.1
    container_name: vault
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
    cap_add:
      - IPC_LOCK
    expose:
      - 8200
    ports:
      - "8200:8200"

  ots:
    build: ./
    container_name: ots
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
      OTS_HTTP_BINDING_ADDRESS: ":8080"
    ports:
      - "8080:8080"
    depends_on:
      - vault
