name: docker image dockle scan

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["docker image build and push"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan-docker-image-dockle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        image_tag: ["latest"]
    steps:
      - name: Run dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}
          format: "list"
          exit-code: "1"
          exit-level: "info"
          ignore: "DKL-DI-0006,CIS-DI-0005"
