name: docker image trivy scan

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["docker image build and push"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan-docker-image-trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        image_tag: ["latest"]
    steps:
      - name: run trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: false
          vuln-type: "os,library"
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
