name: Scan Docker image

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker image"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_CONTENT_TRUST: 1

jobs:
  scan-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        image_tag: ["latest"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scan Docker image
        uses: Azure/container-scan@v0
        with:
          image-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
